version: '3'

services:
  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mdp@2020
      MYSQL_DATABASE: 'typeOrmMDB'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 82:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
